### ISSUE TITLE
wecker im app-store: probleme beim testen

### ISSUE THREAD

**Issue by diplix** [MrJohnZoidberg/Snips-Wecker#2]
zwei probleme fielen gleich zu anfang auf, nachdem ich die app in meinem assistenten installiert habe (wobei ich mir nicht sicher bin, ob das erste eventuell gar kein problem ist): die permissions für 	

`/var/lib/snips/skills/Snips-Wecker/.saved_alarms.json`
`/var/lib/snips/skills/Snips-Wecker/.temporary_ringtone `

scheinen nicht zu funktionieren.

```
(venv) pi@ivanka:/var/lib/snips/skills/Snips-Wecker $ ./action-domi-Wecker.py 
Traceback (most recent call last):
  File "./action-domi-Wecker.py", line 114, in <module>
    alarmclock = AlarmClock(config)
  File "/var/lib/snips/skills/Snips-Wecker/alarmclock/alarmclock.py", line 20, in __init__
    self.ringtone_wav = utils.edit_volume("alarm-sound.wav", self.config['ringing_volume'])
  File "/var/lib/snips/skills/Snips-Wecker/alarmclock/utils.py", line 113, in edit_volume
    wav_file = open(".temporary_ringtone", "r+w")
IOError: [Errno 13] Permission denied: '.temporary_ringtone'

```
nachdem ich die auf 777 gesetzt habe, antwortete mir der wecker. der fehler kann aber auch daran liegen, dass ich die action als user pi aufgerufen habe und das ownership (eigentlich korrekt) auf _snips-skills gesetzt war.

das andere problem: egal ob ich die `config.ini` in 

`/usr/share/snips/assistant/snippets/domi.Alarme_&_Wecker/config.ini`

oder 

`/var/lib/snips/skills/Snips-Wecker/config.ini`

oder

`/var/lib/snips/skills/Snips-Wecker/config.ini.default`

ändere, alle werte werden nach einem 

`sam update-assistant` wieder auf die default-werte zurückgesetzt.

der einzige weg wie ich den wecker zum laufen bringen konnte war die 

`/var/lib/snips/skills/Snips-Wecker/config.ini`

an meinen multiroom-setup anzupassen und dann den snips skill-server neuzustarten. dann bekam ich antworten auf meine eingaben.

```
[global]
ringing_volume=50
ringing_timeout=30s
dict_site-id=Küche:ivanka, Kinderzimmer:ivan
default_room=Küche
restore_alarms=yes
ringtone_status=on
snooze_config=state:off
[secret]

```
aber der multiroom setup funktioniert nicht, wenn ich einen raum nenne, schafft die action nicht den raum aufzulösen:

```
(venv) pi@ivanka:/var/lib/snips/skills/Snips-Wecker $ ./action-domi-Wecker.py 
Traceback (most recent call last):
  File "./action-domi-Wecker.py", line 121, in <module>
    mqtt_client.loop_forever()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "./action-domi-Wecker.py", line 52, in on_message_intent
    say(session_id, alarmclock.new_alarm(slots, data['siteId']))
  File "/var/lib/snips/skills/Snips-Wecker/alarmclock/alarmclock.py", line 79, in new_alarm
    room_slot = slots['room']['value'].encode('utf8')
TypeError: string indices must be integers

```
was allerdings geht: „stelle einen wecker auf 9:30 uhr“ legt einen wecker im default-raum (siteId ivanka) an.

das löschen von alarmen geht wiederrum nicht, weil sich snips in die antwort auf „sicher?“ reinquatscht. das protokolliert sam watch:

```
[09:28:56] [Asr] was asked to listen on site ivanka
[09:28:59] [Asr] captured text "lösche alle alarme" in 2.0s
[09:28:59] [Asr] was asked to stop listening on site ivanka
[09:28:59] [Nlu] was asked to parse input "lösche alle alarme"
[09:28:59] [Nlu] detected intent domi:deleteAlarms with probability 0.958 for input "lösche alle alarme"
[09:28:59] [Dialogue] New intent detected domi:deleteAlarms with probability 0.958
[09:28:59] [Dialogue] was ask to continue session with id dddd936c-2895-4d4e-89db-89da236ecd0c by saying 'Es gibt 3 Alarme. Bist du dir sicher?'
[09:28:59] [Asr] was asked to stop listening on site ivanka
[09:28:59] [Hotword] was asked to toggle itself 'off' on site ivanka
[09:28:59] [Tts] was asked to say "Es gibt 3 Alarme. Bist du dir sicher?"
[09:28:59] [AudioServer] was asked to play a wav of 114.8 kB with id 'U7L70KP4FHJ2NOHT' on site ivanka
[09:28:59] [Tts] finished speaking with id 'ccc75060-f14c-43c6-a381-597458503e4f'
[09:28:59] [Asr] was asked to listen on site ivanka
[09:29:02] [Asr] captured text "es gegen drei alarme" in 2.0s
[09:29:02] [Asr] was asked to stop listening on site ivanka
[09:29:02] [Nlu] was asked to parse input "es gegen drei alarme"
[09:29:02] [Nlu] intent not recognized for "es gegen drei alarme"
[09:29:02] [Dialogue] session with id 'dddd936c-2895-4d4e-89db-89da236ecd0c' was ended on site ivanka. The session was ended because the platform didn't understand the user

```
was natürlich auch schön wäre, wenn man den skill forken könnte. vorbereitet hast du das ja schon, mit deiner `USERNAME_INTENTS` konstante.

letzte anmerkung: wenn der alarm klingelt wird der ringtone sehr schnell hintereinander abgespielt. pausen zwischen den einzelnen ringtones würden es einfacher machen das hotword zu erkennen. währen der alarm spielt erkennt snips das hotword schwer (ausser man schreit).

**Comment by dominiczedler** [comment]
Hi diplix, ich zitiere mal die Probleme und antworte jeweils darauf:

> die permissions [...] scheinen nicht zu funktionieren.

Das Problem tritt, wie du vermutest, nur auf, wenn die action mit dem user Pi gestartet wird. Mit dem user von dem snips-skill-server funktioniert es. Ich weiß leider (noch) nicht, wie man das Problem lösen kann.

> alle werte werden nach einem `sam update-assistant` wieder auf die default-werte zurückgesetzt.

Du hast ja die `config.ini` so mit einem Editor geändert, aber eigentlich hab ich es mir so gedacht, dass man die Parameter in der Snips Console ändert und dann die Einstellungen mit `sam update-assistant` oder `sam install skills` in die `config.ini` übernommen werden.
Ich vermute, dass die Ursache für dein Problem [diese](https://github.com/MrJohnZoidberg/Snips-Wecker/blob/367c19a8e0be957cf5f73776fb16cb4ddbdf71c0/setup.sh#L32) Zeilen sind.
- `/usr/share/snips/assistant/snippets/domi.Alarme_&_Wecker/config.ini` wird mit oben genannten Update-Befehlen mit der neuen Datei von der Snips Console überschrieben (weil das Assistant-Paket entpackt wird und alles alte dann weg ist).
- Wenn die gerade genannte Datei verfügbar ist, wird diese nach `/var/lib/snips/skills/Snips-Wecker/config.ini` kopiert, wenn nicht, wird die Datei `/var/lib/snips/skills/Snips-Wecker/config.ini.default` genommen.

Also da mit `sam update-assistant` deine Einstellungen in `/usr/share/snips/assistant/snippets/domi.Alarme_&_Wecker/config.ini` mit der Datei aus der Console überschrieben wurden, die Datei aber verfügbar war, wurden die voreingestellten Werte aus der Console in die `/var/lib/snips/skills/Snips-Wecker/config.ini` geschrieben.
Zur Lösung solltest du die Einstellungen in der Console ändern. Übrigens: Nach meiner Erfahrung wird die Datei `setup.sh` und damit [diese](https://github.com/MrJohnZoidberg/Snips-Wecker/blob/367c19a8e0be957cf5f73776fb16cb4ddbdf71c0/setup.sh#L32) Zeilen immer ausgeführt, wenn bei SAM "Generating virtual environment for <App>" steht.

 > aber der multiroom setup funktioniert nicht, wenn ich einen raum nenne, schafft die action nicht den raum aufzulösen

Das schau ich mir mal an.

> das löschen von alarmen geht wiederrum nicht, weil sich snips in die antwort auf „sicher?“ reinquatscht.

Ist mir bisher nur beim Programmieren der Snooze-Funktion aufgefallen. Das ist sehr merkwürdig, weil Snips ja praktisch schon die ASR anschaltet, bevor es auf eine Anwort hören sollte (ich kann da von der Programmierung her irgendwie nichts ändern). Das liegt definitiv an dem [MQTT-Befehl](https://github.com/MrJohnZoidberg/Snips-Wecker/blob/367c19a8e0be957cf5f73776fb16cb4ddbdf71c0/action-domi-Wecker.py#L107) `continueSession`, denn mit dem gab es wie oben genannt auch bei Snooze Probleme. Schau ich auch bald an.

> was natürlich auch schön wäre, wenn man den skill forken könnte. vorbereitet hast du das ja schon, mit deiner USERNAME_INTENTS konstante.

Das verstehe ich, aber wenn ich für neue Funktionen noch neue Parameter in der `config.ini` und damit in der Console hinzufüge, tauchen die bei den davor gemachten Forks in der Console nicht mehr auf, obwohl die vielleicht das Programm nicht verändert haben. Also bei dieser App warte ich damit mal vorerst. Mir kannst du jedenfalls alle Sätze und Funktionen schreiben, die das Programm können soll - da ist das Forken ja eigentlich nicht so wichtig.

> wenn der alarm klingelt wird der ringtone sehr schnell hintereinander abgespielt. pausen zwischen den einzelnen ringtones würden es einfacher machen das hotword zu erkennen.

Das werde ich ändern, indem ich bei der Sound-Datei eine größere Pause am Ende einfüge oder im Programm eine Pause mache - mal sehen, was besser ist.

> währen der alarm spielt erkennt snips das hotword schwer (ausser man schreit).

Das liegt vermutlich daran, dass der Ringtone viele Höhen enthält und die sich mit der Stimme vermischen. Du kannst es mit Echo Cancelling versuchen, da wird das, was abgespielt wird, aus der Aufnahme rausgefiltert. Leider ist das etwas aufwendiger und es funktioniert nicht immer sofort.
[Hier](https://forum.snips.ai/t/microphone-for-room-with-music/614/43) gibt es zu dem Thema eine Diskussion im Forum. Wenn du das Respeaker Mic Array 2.0 hast und der Sound darüber abgespielt wird, wird dort schon auf der Hardware der abgespielte Sound aus dem Mikrofon-Stream gefiltert.
Wenn eine längere Pause zwischen den Ringtones ist, sollte das Problem aber nicht mehr so groß sein :-)

Danke für deine Rückmeldung, so etwas ist immer hilfreich.

**Comment by diplix** [comment]
danke, dass man die config.ini-werte in der console ändern kann ohne den skill zu forken hab ich übersehen (zu wenig gescrollt). das hilft auf jeden fall schonmal weiter. 
und danke für die ausführlichen antworten. wenn mir mehr auffällt oder sich probleme lösen sag ich gerne nochmal bescheid.

**Comment by diplix** [comment]
super, mit der konsolen-konfiguration klappts auf anhieb, aber leider kann ich das raum-problem reproduzieren. wenn ich sage „stelle einen wecker im kinderzimmer auf 6 uhr“ timed der skill aus und antwortet danach auch nicht mehr. scheint also abgestürzt zu sein, mit der fehlermeldung die ich oben zitiert habe. nur ein `sudo systemctl restart snips-skill-server.service` belebt den skill dann wieder. vielleicht sollte ich es mal mit raumnamen ohne umlaut probieren?

<img width="717" alt="bildschirmfoto 2018-12-09 um 22 08 37" src="https://user-images.githubusercontent.com/4541494/49702941-14437e80-fbff-11e8-9a09-c4bb949e2f80.png">

**Comment by dominiczedler** [comment]
Das war ein Fehler im Code, hab ihn jetzt weggemacht ([Commit](https://github.com/MrJohnZoidberg/Snips-Wecker/commit/91b1c05838c5335052cdae5430f49fbb34608595)).

**Comment by dominiczedler** [comment]
Probier mal bitte nochmal, alle Alarme zu löschen. Bei mir funktioniert das jetzt, obwohl ich nichts an der Stelle im Code geändert habe. :thinking:

**Comment by diplix** [comment]
kann sein dass meine snips.toml konfiguration hier dazwischen funkt, muss ich nochmal ausprobieren den derzeitigen wert zurück auf default zu setzen, derzeit habe ich

```
[snips-dialogue]
#resources = "/usr/share/snips/dialogue"
# session_timeout = 15
# lambda_timeout = 5
retry_count = 1
sound_feedback_enabled_default = false
```
und eine etwas modifizierte hotwort-erkennung. und damit ergibt sich noch das gleiche bild:
```
[20:34:34] [Asr] was asked to stop listening on site ivanka
[20:34:34] [Hotword] was asked to toggle itself 'off' on site ivanka
[20:34:34] [Tts] was asked to say "Es gibt 2 Alarme. Bist du dir sicher?"
[20:34:35] [AudioServer] was asked to play a wav of 120.4 kB with id 'CT49XC8O4VH9T0WK' on site ivanka
[20:34:35] [Tts] finished speaking with id '2467e7ad-9493-401d-bfd5-bfac698e5538'
[20:34:35] [Asr] was asked to listen on site ivanka
[20:34:38] [Asr] captured text "zwei" in 2.0s
[20:34:38] [Asr] was asked to stop listening on site ivanka
[20:34:38] [Nlu] was asked to parse input "zwei"
[20:34:38] [Nlu] intent not recognized for "zwei"
[20:34:38] [Dialogue] session with id '77713dbc-d24d-488c-a0c0-40d5d466ae08' was ended on site ivanka. The session was ended because the platform didn't understand the user
[20:34:38] [Asr] was asked to stop listening on site ivanka
[20:34:38] [Hotword] was asked to toggle itself 'on' on site ivanka
[20:34:39] [AudioServer] finished playing wav with id 'CT49XC8O4VH9T0WK'
```

**Comment by dominiczedler** [comment]
Ich vermute, dass das nicht an meinem Programm, sondern an Snips liegt. Ich schreibe demnächst mal etwas dazu ins Forum, vielleicht reagieren die von Snips ja darauf. Bei den Issues [hier](https://github.com/snipsco/snips-issues/issues) auf Github weiß ich noch weniger ob es gelesen wird.

**Comment by diplix** [comment]
ich schaffe es den wecker skill mit dieser bitte zum absturz zu bringen, die python fehlermeldung habe ich nicht parat, aber ich denke du müsstest das reproduzieren können:

```
[00:09:21] [Asr] captured text "stelle morgen früh einen wecker um acht" in 4.0s
[00:09:21] [Asr] was asked to stop listening on site ivanka
[00:09:21] [Nlu] was asked to parse input "stelle morgen früh einen wecker um acht"
[00:09:21] [Nlu] detected intent domi:newAlarm with probability 0.487 for input "stelle morgen früh einen wecker um acht"
              Slots ->
                 time -> 2018-12-12 01:00:00 +01:00 (confidence: 0.797)
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.965)
[00:09:21] [Dialogue] New intent detected domi:newAlarm with probability 0.487
              Slots ->
                 time -> 2018-12-12 01:00:00 +01:00 (confidence: 0.797)
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.965)
[00:09:27] [Dialogue] session with id '078650fa-3270-4b91-a696-b04456456610' was ended on site ivanka. The session was ended because one of the component didn't respond in a timely manner
```

das geht:

```
[00:23:24] [Asr] captured text "stelle einen wecker auf acht uhr morgens" in 3.0s
[00:23:24] [Asr] was asked to stop listening on site ivanka
[00:23:24] [Nlu] was asked to parse input "stelle einen wecker auf acht uhr morgens"
[00:23:24] [Nlu] detected intent domi:newAlarm with probability 0.511 for input "stelle einen wecker auf acht uhr morgens"
              Slots ->
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.951)
[00:23:24] [Dialogue] New intent detected domi:newAlarm with probability 0.511
              Slots ->
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.951)
[00:23:24] [Dialogue] was ask to end session with id 81feaf2e-885b-4bbe-87a6-aab7e038772c by saying 'Der Wecker wird in 7 Stunden und 37 Minuten um 8 Uhr klingeln.'
[00:23:24] [Tts] was asked to say "Der Wecker wird in 7 Stunden und 37 Minuten um 8 Uhr klingeln."
[00:23:25] [AudioServer] was asked to play a wav of 208.2 kB with id 'PE4L4DJ3IUMOQ0N6' on site ivanka
[00:23:25] [Tts] finished speaking with id '9130f69a-99b7-4db2-9ed6-a6e46ea14292'
[00:23:25] [Dialogue] session with id '81feaf2e-885b-4bbe-87a6-aab7e038772c' was ended on site ivanka. The session ended as expected
[00:23:25] [Asr] was asked to stop listening on site ivanka
[00:23:25] [Hotword] was asked to toggle itself 'on' on site ivanka
```

insgesamt scheinen die letzten commits den skill etwas instabilisiert zu haben. ich kann auch einen absturz des skills provozieren wenn ich den acht uhr wecker lösche (ging vorher mal):

```
[00:34:59] [Asr] captured text "wecker um acht uhr löschen" in 3.0s
[00:34:59] [Asr] was asked to stop listening on site ivanka
[00:34:59] [Nlu] was asked to parse input "wecker um acht uhr löschen"
[00:34:59] [Nlu] detected intent domi:deleteAlarms with probability 0.316 for input "wecker um acht uhr löschen"
              Slots ->
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.787)
[00:34:59] [Dialogue] New intent detected domi:deleteAlarms with probability 0.316
              Slots ->
                 time -> 2018-12-11 08:00:00 +01:00 (confidence: 0.787)
[00:35:05] [Dialogue] session with id '61a6b5e9-fe22-485b-8fcb-11fb84eea193' was ended on site ivanka. The session was ended because one of the component didn't respond in a timely manner
``` 

passiert auch nachdem ich den skill neu installiert habe …

**Comment by diplix** [comment]
hm. irgendwas stimmt mit der config ini nicht. tatsächlich hat die konsole meine variablen überschrieben. mit neu gesetzten variablen entsteht diese konfiguration:

```
[global]
ringing_volume=50
ringing_timeout=30s
dict_site-id=Küche:ivanka,Kinderzimmer:ivan
default_room=Küche
restore_alarms=yes
ringtone_status=on
snooze_config=state:off
[secret]
```

aber der skill hat noch irgendwie die idee von einer default siteId:

```
(venv) pi@ivanka:/var/lib/snips/skills/Snips-Wecker $ ./action-domi-Wecker.py 
Traceback (most recent call last):
  File "./action-domi-Wecker.py", line 121, in <module>
    mqtt_client.loop_forever()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1578, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1072, in loop
    rc = self.loop_read(max_packets)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1374, in loop_read
    rc = self._packet_read()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2071, in _packet_read
    rc = self._packet_handle()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2560, in _packet_handle
    return self._handle_publish()
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2759, in _handle_publish
    self._handle_on_message(message)
  File "/var/lib/snips/skills/Snips-Wecker/venv/local/lib/python2.7/site-packages/paho/mqtt/client.py", line 2902, in _handle_on_message
    callback(self, self._userdata, message)
  File "./action-domi-Wecker.py", line 56, in on_message_intent
    say(session_id, alarmclock.get_alarms(slots, data['siteId']))
  File "/var/lib/snips/skills/Snips-Wecker/alarmclock/alarmclock.py", line 193, in get_alarms
    room_part = self.get_roomstr(filtered_alarms[dtobj], siteid)
  File "/var/lib/snips/skills/Snips-Wecker/alarmclock/alarmclock.py", line 680, in get_roomstr
    current_room_prepos = self.translation.get_prepos(self.dict_rooms[iter_siteid])
KeyError: u'default'

```

**Comment by dominiczedler** [comment]
Könntest du zu dem letzten Problem bitte schreiben, durch welchen Satz es ausgelöst wird?

**Comment by diplix** [comment]
ich glaube das letzte problem wurde durch „wecker um acht uhr löschen“ getriggert. ich erinnere mich aber nicht mehr zu 100% und versuche das heute abend nochmal mit verschiedenen sätzen durchzuspielen.

kennst du eine bessere methode deinen skill, bzw. skllls und snippets aus dem app-store zu debuggen (logs) als das action-script im venv aufzurufen? ich konnte dazu bisher nix finden.

**Comment by diplix** [comment]
strange. jetzt geht alles. nichts verändert, alle sätze die vor zwei tagen probleme zu verursachen schienen gehen jetzt. frag mich nicht. neustart und update-assistant hatte ich vor zwei tagen auch durchgeführt. ich schliesse das jetzt hier, weil du ja für die offenen punkte eigene issues angelegt hast.
